-- MySQL Script generated by MySQL Workbench
-- dom 05 nov 2023 12:13:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Optica` ;

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Customer` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(20) NULL,
  `address` VARCHAR(200) NULL,
  `registrationDate` DATE NOT NULL,
  `referrerCustomerID` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_1_idx` (`referrerCustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_1`
    FOREIGN KEY (`referrerCustomerID`)
    REFERENCES `Optica`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Provider` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Provider` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `postCode` VARCHAR(15) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(20) NOT NULL,
  `NIF` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Brand` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Brand` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `id_provider` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Brand_1_idx` (`id_provider` ASC) VISIBLE,
  CONSTRAINT `fk_Brand_1`
    FOREIGN KEY (`id_provider`)
    REFERENCES `Optica`.`Provider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`glasses_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`glasses_model` ;

CREATE TABLE IF NOT EXISTS `Optica`.`glasses_model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(50) NOT NULL,
  `leftLensGrade` DECIMAL(4,2) NOT NULL,
  `rightLensGrade` DECIMAL(4,2) NOT NULL,
  `frameType` ENUM("floating", "plastic", "metal") NOT NULL,
  `frameColor` VARCHAR(45) NOT NULL,
  `lensColor` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `idBrand` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_glasses_model_1_idx` (`idBrand` ASC) VISIBLE,
  CONSTRAINT `fk_glasses_model_1`
    FOREIGN KEY (`idBrand`)
    REFERENCES `Optica`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Employee` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `surName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Sales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica`.`Sales` ;

CREATE TABLE IF NOT EXISTS `Optica`.`Sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idglasses` INT NOT NULL,
  `idcustomer` INT NOT NULL,
  `idemployee` INT NOT NULL,
  `saleDate` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sales_1_idx` (`idglasses` ASC) VISIBLE,
  INDEX `fk_Sales_2_idx` (`idcustomer` ASC) VISIBLE,
  INDEX `fk_Sales_3_idx` (`idemployee` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_1`
    FOREIGN KEY (`idglasses`)
    REFERENCES `Optica`.`glasses_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales_2`
    FOREIGN KEY (`idcustomer`)
    REFERENCES `Optica`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sales_3`
    FOREIGN KEY (`idemployee`)
    REFERENCES `Optica`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
